permalink: /:title/
collections:
  cuvees:
    output: true

defaults:
  - scope:
      path: ""
      type: "cuvees"
    values:
      layout: "cuvee"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
